### ISSUE TITLE
linux - fedora don't see this engine 

### ISSUE THREAD

**Issue by catafest** [wsmind/leaf#6]
I try to use this engine with Fedora 27 
I download the zip file from github and I used User Preferences to add it. 
The addon is add to addons folder but the blender don't see anything into User Preferences main menu.

**Comment by wsmind** [comment]
Hello Cătălin,

This engine is written using DirectX 11, and hence is compatible with Windows (7 and above) only. Porting to other platforms is not part of the future development plans as of now.

Sorry about that.
